[package]
name = "serde_kdlab_xprm"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }

[features]
default = ["std"]
std = ["serde/std"]
alloc = ["serde/alloc"]
